### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by hnk** [Kloadut/SSOwat#17]
All of a sudden, my ynh instance is utterly broken.

When trying to access /yunohost/soo it fails with a generic 500 error. 
*/var/log/nginx/___-error.log* displays:
```
[error] 2445#0: *26 lua entry thread aborted: runtime error: /usr/share/ssowat/access.lua:413: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/usr/share/ssowat/access.lua:413: in function 'get_data_for'
	/usr/share/ssowat/access.lua:367: in function 'serve'
	/usr/share/ssowat/access.lua:839: in function </usr/share/ssowat/access.lua:1>, client: 37.***.***.***, server: ***********, request: "GET /ynhpanel.json HTTP/1.1", host: "*****", referrer: "*********"
```

Also when trying to reach only my base domain I only receive a standard "Welcome to nginx!" page. No more redirection to the portal.

Cannot find any other relevant logs at the moment.

**Comment by titul** [comment]
Same error, restart nginx fix temporary the bug :
2015/05/15 14:10:39 [error] 676#0: *3127 lua entry thread aborted: runtime error: /usr/share/ssowat/helpers.lua:459: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'pairs'
        /usr/share/ssowat/helpers.lua:459: in function 'get_data_for'
        /usr/share/ssowat/helpers.lua:395: in function </usr/share/ssowat/helpers.lua:344>, client: X.X.X.X, server: plop.fr, request: "GET /yunohost/sso/ HTTP/1.1", host: "plop.fr"
2015/05/15 14:13:51 [error] 671#0: *3138 lua entry thread aborted: runtime error: /usr/share/ssowat/helpers.lua:459: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'pairs'
        /usr/share/ssowat/helpers.lua:459: in function 'get_data_for'
        /usr/share/ssowat/helpers.lua:395: in function </usr/share/ssowat/helpers.lua:344>, client: X.X.X.X, server: plop.fr, request: "GET /yunohost/sso/ HTTP/1.1", host: "plop.fr"

**Comment by opi** [comment]
Seems to be fixed or outdated. Feel free to reopen if not, thanks
