### ISSUE TITLE
Add SSOwat as plugin for Kong

### ISSUE THREAD

**Issue by sinzone** [Kloadut/SSOwat#42]
would be cool to have it as a plugin (https://getkong.org/plugins ) for https://github.com/Mashape/kong

LDAP issue: https://github.com/Mashape/kong/issues/329

**Comment by opi** [comment]
Closing issue because this is out of scope for us. SSowat is mainly used as YunoHost SSO service, and we don't have any spare time to extend it, but please feel free to fork this repository ;)
