### ISSUE TITLE
unprotected_urls is not working ?

### ISSUE THREAD

**Issue by src386** [Kloadut/SSOwat#49]
To make it simple, let's pretend that I want to access the following page even if I am not logged in Yunohost : https://src386.org/movim .

In /etc/yunohost/apps/movim/settings.yml : 
skipped_uris: /       --> works, I can access my URL.
unprotected_urls: /     --> doesn't work, I am redirected to the Yunohost portal.

According to the documentation, skipped_urls just ignores SSO, and unprotected_urls try to use credentials if user is logged but ignores SSO if not.

**Comment by src386** [comment]
It's working with unprotected_uris.
That is confusing... but I guess it's normal.

**Comment by mbugeia** [comment]
I think everything works as intended but it's a little confusing, see this https://dev.yunohost.org/issues/60 and this https://github.com/YunoHost/yunohost/blob/unstable/src/yunohost/app.py#L987-L1012

**Comment by src386** [comment]
It's okay for me. Thanks.
