### ISSUE TITLE
skipped_regex... how does it works ?

### ISSUE THREAD

**Issue by src386** [Kloadut/SSOwat#50]
Hi,
I want _skipped_regex_ to match if the URL contains **movim** AND **login**.
Using regex101.com I think this regex should work : 

    ^(?=.*\bmovim\b)(?=.*\blogin\b).*$

So I tried : 

    yunohost app setting movim skipped_regex -v "^(?=.*\bmovim\b)(?=.*\blogin\b).*$"

Or even direct edit /etc/yunohost/apps/movim/settings.yml : 

    skipped_regex: ^(?=.*\bmovim\b)(?=.*\blogin\b).*$

I tried to add '' or "", even // but this does not working.

I use the _yunohost app ssowatconf_ and _service nginx reload_ commands after each try.

**Comment by opi** [comment]
See https://github.com/Kloadut/SSOwat/pull/44 , SSOwat regex are not regular PCRE regex but use Lua regex syntax.
