### ISSUE TITLE
Portal on non-statndard port

### ISSUE THREAD

**Issue by barrybingo** [Kloadut/SSOwat#52]
In access.lua you have these matches
```lua
   if ngx.var.host == conf["portal_domain"]
```
and these will fail if portal_domain is something like myserver.com:9999 as ngx.var.host does not include port number.

So I changed the portal_domain to without the port number but then the redirect goes to the domain on standard port.... aghghgh :)
This is because in config.lua you construct the redirect url with
```lua
   conf.portal_url = conf["portal_scheme"].."://"..
                      conf["portal_domain"]..
                      conf["portal_path"]
```

**Comment by opi** [comment]
Using the portal on a non-standard port is not in the scope of SSOwat/Yunohost, but if you manage to have a `conf["portal_port"]` settings that works, We'll be happy to review and merge your code.
I'm closing the issue as I'm doing some triage and cleanup right now, but feel free to re-open it, or even better to submit a pull request :)
